packages:
  - server
  - client

allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  vue-demi: set this to true or false

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
  - vue-demi
